---
abstract: 'Simple, versioned access to configuration data'
author:
  - 'Scott T. Hardin, C<< <mrscotty at hnsc.de> >>'
  - 'Scott T. Hardin <mrscotty@hnsc.de>'
build_requires:
  DateTime: 0
  ExtUtils::MakeMaker: 6.42
  Path::Class: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Config-Versioned
no_index:
  directory:
    - inc
    - t
recommends:
  Config::Any: 0
  Config::Merge: 0
  YAML::XS: 0
requires:
  Git::PurePerl: 0
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
